lexer grammar LizLangLexer;

fragment IDENTIFIER_BODY: IDENTIFIER_START | DIGIT;
fragment IDENTIFIER_START: [A-Za-z$_];
fragment DIGIT: [0-9];
fragment UNDERSCORE: '_';
IDENTIFIER: IDENTIFIER_START IDENTIFIER_BODY*;
INTEGER:
    (DIGIT (DIGIT | UNDERSCORE)+ DIGIT)
|   (DIGIT+)
;